spring:
  profiles:
    include: secret

app:
  push:
    waitTime: 150
    computeTime: 20
firebase:
  file:
    name: firebase/dandi-4158a-firebase-adminsdk-h61xd-7ec9de5fad.json

noti:
  until:
    time: 3
  jpa:
    properties:
      .hibernate:
        cache:
          region:
            timeToLiveSeconds: 3600
          use_second_level_cache: true
  profiles:
    include: secret

  h2:
    console:
      enabled: true
      path: /h2-console

route:
  max-radius: 1000