spring:
  profiles:
    include: secret
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.cache.use_second_level_cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  push:
    waitTime: 150
    computeTime: 20
firebase:
  file:
    name: firebase/dandi-8be67-firebase-adminsdk-m922n-ff8ee2fea7.json

noti:
  until:
    time: 3

  h2:
    console:
      enabled: true
      path: /h2-console

route:
  max-radius: 1000
  distance-threshold: 800