firebase:
  file:
    name: firebase/dandi-8be67-firebase-adminsdk-m922n-ff8ee2fea7.json

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

noti:
  until:
    time: 3
